# Generated by Django 2.2.7 on 2020-01-21 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='created',
            new_name='uploaded',
        ),
    ]
